### ISSUE TITLE
cannot start the app

### ISSUE THREAD

**Issue by Hector6704** [AxonTeam/GitHookAPI#1]
hi, the app doesn't start, and the only error I get is that 
![applicationframehost_2019-01-15_10-51-14](https://user-images.githubusercontent.com/42733258/51172527-b23c0000-18b3-11e9-93af-603641ecf965.png)

**Comment by Khaaz** [comment]
First of all I want to highlight that this repository will not be meant to be selfhosted (or at least not in the same way as right now). So you might not be able to keep using this code in the future.
However this repository is a copy of https://github.com/Khaazz/Git-Discord-HookRouter. Both repository will diverge more in the future.

As for that error, it seems that your process is receiving a SIGINT signal.
Are you using last version of pm2?
What is your node version?
How are you starting the app?
And did you create the configs as specified in the readme?

**Comment by Hector6704** [comment]
Node and pm2 seem up to date, I'm starting the app with `pm2 start scripts/start.js` 
My configs are right

**Comment by Hector6704** [comment]
Also sqlite3 was missing in the dependencies

**Comment by Khaaz** [comment]
We don't require sqlite? Are you sure you are running a clean version of this code?

**Comment by Hector6704** [comment]
Hm yeah, I cooked this repo and idk but it asked me to install sqlite3

**Comment by Santhosh-Annamalai** [comment]
Hello! Can you try starting your app without pm2? Just to see what the outcome will be? Also make sure you follow step by step instructions given in readme. Just to make sure everything is set alright

**Comment by Santhosh-Annamalai** [comment]
Also, what version of node are you using? It seems like it marked http2 as an experimental API while in fact it is a [Stable API](https://nodejs.org/dist/latest-v10.x/docs/api/http2.html#http2_http_2)

**Comment by Hector6704** [comment]
I'm getting that error now
![image](https://user-images.githubusercontent.com/42733258/51196558-a8d08900-18ef-11e9-9550-d35da0a0f5dd.png)
I'm using node v.10.14.1

**Comment by Santhosh-Annamalai** [comment]
It seems like you haven't installed express. Try using `npm install --production --no-optional` or `yarn install --production --ignore-optional` if you're using yarn and try again. Make sure you follow instructions in readme. Also make sure you update your node version to v10.15.0 since that's the LTS version of node.

**Comment by Hector6704** [comment]
![image](https://user-images.githubusercontent.com/42733258/51197107-f13c7680-18f0-11e9-8aec-c958b0cbad21.png)

**Comment by Santhosh-Annamalai** [comment]
It seems like you may be having a lock file with unresolved conflicts. Try removing previously generated `package-lock.json` file and try that command again.

**Comment by Hector6704** [comment]
![image](https://user-images.githubusercontent.com/42733258/51198250-06ff6b00-18f4-11e9-9ce9-66c2d955c6f4.png)

**Comment by Hector6704** [comment]
![image](https://user-images.githubusercontent.com/42733258/51198289-28605700-18f4-11e9-9b36-177ce3d5f8ef.png)

**Comment by Santhosh-Annamalai** [comment]
Seems like your clone of the project is messed up as it doesn't have a package.json file. Try deleting that clone and follow the instructions below.
```
git clone https://github.com/AxonTeam/GitHookAPI.git
cd GitHookAPI
npm install --production --ignore-optional
```
And follow the instructions [here](https://github.com/AxonTeam/GitHookAPI#instructions-on-setting-it-up).

**Comment by Hector6704** [comment]
ok, I did that but now I'm receiving the same error as https://github.com/AxonTeam/GitHookAPI/issues/1#issuecomment-454472380 when I try to install the dependencies

**Comment by Santhosh-Annamalai** [comment]
Try clearing cache using `npm cache clean --force` and try `npm install --production --ignore-optional` and follow [these](https://github.com/AxonTeam/GitHookAPI#instructions-on-setting-it-up) instructions.

**Comment by Santhosh-Annamalai** [comment]
Closing issue as cleaning npm cache fixed their problem
